spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/ot111_ong
        username: postgres
        password: postgres
    jpa:
        show-sql: true


amazonProperties:
    endpointUrl: https://s3.us-east-1.amazonaws.com
    aws.accessKey: ${ACCESS_KEY:access-key}
    aws.secretKey: ${SECRET_KEY:secret-key}
    aws.region: us-east-1
    aws.bucketName: ${BUCKET_NAME:bucket-name}


sendgrid:
    sendgrid.apiKey: ${SG_API_KEY:12345}
    sendgrid.sender: ${SG_SENDER:12345}
    welcome-template: ${SG_TEMPLATE_ID:12345}


#Swagger Configurations
springdoc:
    api-docs:
        path: /api/docs #path para consultar springdoc-openapi doc
    swagger-ui:
        path: /api/docs/swagger-ui.html # path para consultar swagger-ui
        enabled: true #para produccion conviene desactivar swagger-ui (o trabajarla en otro puerto)

